config/routes.rb
Rails.application.routes.draw do

  resources :companies do
    resources :branches, only: [:new, :create, :edit, :update]
  end
  # get 'branches/index'
  # get 'branches/show'
  # get 'branches/new'
  # get 'branches/create'
  # get 'branches/edit'
  # get 'branches/update'
  # get 'branches/destroy'

  # resources :companies

  # get 'companies/index'
  # get 'companies/show'
  # get 'companies/new'
  # get 'companies/create'
  # get 'companies/edit'
  # get 'companies/update'
  # get 'companies/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  validates :name, presence: true
  validates :tin_number, presence: true
  belongs_to :branchable, polymorphic: true
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
  has_many :branches, as: :branchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @branchable = branchable
    @branch = @branchable.branches.new
  end

  def create
    @branchable = branchable
    @branch = @branchable.branches.new(branch_params)

    if @branch.save
      redirect_to branchable_url(branchable), notice: "The branch has been successfully created."
    end
  end

  def edit
    @branchable = branchable
    @branch = branchable.branches.find(params[:id])
  end

  def update
    @branchable = branchable
    @branch = @branchable.branches.find(params[:id])
    if @branch.update_attributes(branch_params)
      redirect_to branchable_url(branchable), notice: "The branch has been updated"
    end
  end

  def destroy
  end

  private
    def branch_params
      params.require(:branch).permit!
    end

    def branchable
      if params[:company_id]
        id = params[:company_id]
        Company.find(params[:company_id])

      end
    end

    def branchable_url(branchable)
      if Company === branchable
        company_path(branchable)
      end
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to companies_path, notice: "The company has been successfully created."
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(company_params)
      redirect_to companies_path, notice: "The company has been updated"
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
  end

  private
    def company_params
      params.require(:company).permit!
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/branches/_form.html.erb
<%= form_for [@branchable, @branch] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter a Branch Name." %>
  </div>
  <div class="form-group">
    <%= f.label :tin_number %>
    <%= f.text_field :tin_number, class: "form-control", placeholder: "Enter the TIN of the Branch" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/branches/create.html.erb
<h1>Branches#create</h1>
<p>Find me in app/views/branches/create.html.erb</p>

app/views/branches/destroy.html.erb
<h1>Branches#destroy</h1>
<p>Find me in app/views/branches/destroy.html.erb</p>

app/views/branches/edit.html.erb
<h1>Editing Branch for <%= @branchable.name %></h1>
<%= render "form" %>

<!--
<h1>Branches#edit</h1>
<p>Find me in app/views/branches/edit.html.erb</p>
-->

app/views/branches/index.html.erb
<h1>Branches#index</h1>
<p>Find me in app/views/branches/index.html.erb</p>

app/views/branches/new.html.erb
<h1>New Branch for <%= @branchable.name %></h1>
<%= render "form" %>

<!--
<h1>Branches#new</h1>
<p>Find me in app/views/branches/new.html.erb</p>
-->

app/views/branches/show.html.erb
<h1>Branches#show</h1>
<p>Find me in app/views/branches/show.html.erb</p>

app/views/branches/update.html.erb
<h1>Branches#update</h1>
<p>Find me in app/views/branches/update.html.erb</p>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter a Company Name" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<h1>Editing <%= @company.name %></h1>
<%= render "form" %>

<!--
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>
-->

app/views/companies/index.html.erb
<h1>FullSuite Clients Lists</h1>
<div class="well">
<%= link_to "New Company", new_company_path, class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Branches</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @companies.count == 0 %>
      <tr>
        <td colspan="3">
          No companies found.  Click the button above to add a new one.
        </td>
      </tr>
    <% else %>
      <% @companies.each do |company| %>
        <tr>
          <td><%= link_to "#{company.name}", company %></td>
          <td><%= company.branches.count %> branches found </td>
          <td><%= link_to "View", company_path(company), class: "btn btn-default" %></td>
          <td><%= link_to "View V2", company, class: "btn btn-default" %></td>
          <td><%= link_to "Edit", edit_company_path(company), class: "btn btn-default" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<!--
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>
-->

app/views/companies/new.html.erb
<h1>Add Company</h1>
<%= render "form" %>

<!--
<h1>Companies#new</h1>
<p>Find me in app/views/companies/new.html.erb</p>
-->

app/views/companies/show.html.erb
<h1><%= "#{@company.name}" %></h1>
<hr />
<h3>Branches Lists</h3>
<div class="well">
  <%= link_to "New Branch", new_company_branch_path(@company), class: "btn btn-primary" %>
</div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Branch Name</th>
      <th>Tin Number</th>
      <th>Created On</th>
      <td>&nbsp;</td>
    </tr>
  </thead>
  <% if @company.branches.count > 0 %>
    <% @company.branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.tin_number %></td>
        <td><%= time_ago_in_words branch.created_at %> ago</td>
        <td><%= link_to "Edit", edit_company_branch_path(@company, branch), class: "btn btn-default" %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="2">No branches found for this company.  Click the 'New Branch' button to create a new branch.</td>
    </tr>
  <% end %>
</table>

<!--
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>
-->

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinDirectory Version 6</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", companies_path %></li>
        <li><%= link_to "Companies", companies_path %></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>


  </body>
</html>